name: Scan for Tokens

on:
    push:
      branches: ['**']
    pull_request:
      branches: [ "**" ]

jobs:
  truffle_scan:
    name: Truffle Key Scanner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name:
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD 
